version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.11
  install:
    - requirements: docs/source/requirements.txt

formats: all
